/************************************************************
 * File:    09_pareto_analysis.sql
 * Author:  Maksym Yakushev
 * Date:    2026-09-22
  * Purpose:  Pareto Analysis
 ************************************************************/


-- ============================================================
-- 1. DATA PREVIEW
-- ============================================================

SELECT 
	* 
FROM sales;


-- ============================================================
-- 2. REVENUE BY PRODUCT
-- ============================================================

SELECT
    product
    , SUM(total) AS revenue
FROM sales
GROUP BY 
	product
ORDER BY 
	revenue DESC;


-- ============================================================
-- 3. MAIN PARETO SCRIPT
-- ============================================================

WITH product_sales AS (
    SELECT
        product
        , SUM(total) AS revenue
    FROM sales
    GROUP BY 
		product
),

pareto AS (
    SELECT
        product
        , revenue
        , SUM(revenue) OVER () AS total_revenue
        , SUM(revenue) OVER (ORDER BY revenue DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative_revenue
    FROM product_sales
)

SELECT
    product
    , revenue
    , ROUND(revenue / total_revenue * 100, 2) AS revenue_share
    , ROUND(cumulative_revenue / total_revenue * 100, 2) AS cumulative_revenue_share
FROM pareto
ORDER BY 
	revenue DESC;


-- ============================================================
-- 4. PRODUCT GENERATED BY 80% REVENUE
-- ============================================================

WITH product_sales AS (
    SELECT
        product
        , SUM(total) AS revenue
    FROM sales
    GROUP BY 
		product
),

pareto AS (
    SELECT
        product
        , revenue
        , SUM(revenue) OVER (ORDER BY revenue DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative_revenue
        , SUM(revenue) OVER () AS total_revenue
        , ROW_NUMBER() OVER (ORDER BY revenue DESC) AS product_rank
    FROM product_sales
)

SELECT
    product_rank
    , product
    , revenue
    , ROUND(cumulative_revenue / total_revenue * 100, 2) AS cumulative_revenue_share
FROM pareto
WHERE 
	cumulative_revenue / total_revenue >= 0.80
ORDER BY 
	product_rank
LIMIT 1;


-- ============================================================
-- 5. PARETO BY UNITS SOLD
-- ============================================================

WITH product_sales AS (
    SELECT
        product
        , SUM(units_sold) AS units_sold
    FROM sales
    GROUP BY 
		product
)

SELECT
    product
    , units_sold
    , ROUND(units_sold / SUM(units_sold) OVER () * 100, 2) AS units_share
    , ROUND(SUM(units_sold) OVER (ORDER BY units_sold DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / SUM(units_sold) OVER () * 100, 2) AS cumulative_units_share
FROM product_sales
ORDER BY 
	units_sold DESC;

